### ISSUE TITLE
Release checklist 0.1.0

### ISSUE THREAD

**Issue by karencfv** [oxidecomputer/terraform-provider-oxide#235]
- [x] Make sure all examples and docs reference the new provider version https://github.com/oxidecomputer/terraform-provider-oxide/pull/236
- [x] Make sure version is set to 0.1.0 in VERSION and version.go files https://github.com/oxidecomputer/terraform-provider-oxide/pull/236
- [x] Once released, update Go SDK to v0.1.0-beta2 https://github.com/oxidecomputer/terraform-provider-oxide/pull/237
- [x] Generate changelog https://github.com/oxidecomputer/terraform-provider-oxide/pull/238
- [x] Release the new version https://pkg.go.dev/github.com/oxidecomputer/oxide.go@v0.1.0-beta2
